name: check_code_quality
on: pull_request
jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: |
          python -m pip install --upgrade pip
          pip install black pylint isort
          pip install -r requirements.txt
      - run: |
          black --check --verbose .
          pylint --verbose .
          isort --check --verbose .